apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
  namespace: istio-system
spec:
  hosts:
  - "marketplace.local"
  gateways:
  - hfrontend-gateway
  http:
    - name: "dashboard"
      route:
      - destination:
          host: frontend-dashboard.svc.core.cluster.local
