apiVersion: apps/v1
kind: Deployment
metadata:
  name:  products
spec:
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app:  products
    spec:
      containers:
      - name:  products
        image:  aditirvan/istio-sample-app:products
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080