apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
- namespace.yaml
- ../../../module/helm-repository/grafana/grafana.yaml
- ../../../module/helm-repository/prometheus/repository.yaml
- grafana
- prometheus
