apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
- namespace.yaml
- grafana
- ../../../module/helm-repository/grafana/grafana.yaml
- birnami
- ../../../module/helm-repository/bitnami/bitnami.yaml
