apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: wordpress
spec:
  interval: 1m
  chart:
    spec:
      chart: wordpress
      sourceRef:
        kind: HelmRepository
        name: wordpress
      interval: 5m
  releaseName: wordpress
  values:
    replicas: 1
    service:
      type: LoadBalancer
      port: 80