apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
  namespace: istio-system
spec:
  hosts:
  - "marketplace.local"
  gateways:
  - frontend-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: frontend-dashboard.namespace.svc.cluster.local
        port:
          number: 8080
