apiVersion: helm.toolkit.fluxcd.io/v1beta2
kind: HelmRelease
metadata:
  name: products
spec:
  interval: 1m
  chart:
    spec:
      chart: ./module/helm-application
      sourceRef:
        kind: GitRepository
        name: flux-system
        namspace: flux-system
      interval: 1m
  releaseName: products
  values:
    image: nginx:latest
    ports: 8080