apiVersion: source.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: auth-service
spec:
  interval: 1m
  chart:
    spec:
      chart: ../../../../module/helm-application/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  releaseName: auth-service
  values:
    image: aditirvan/webapp:4
    port: 80