apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistentvolume-controller
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /prometheus/data