apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistentvolume-controller
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: persistentvolume-controller
  hostPath:
    path: /prometheus/data