apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistentvolume-controller
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: persistentvolume-controller
  hostPath:
    path: /prometheus/data

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: persistentvolume-controller
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer