apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus-operator
spec:
  interval: 1m
  chart:
    spec:
      chart: prometheus-operator
      sourceRef:
        kind: HelmRepository
        name: prometheus-operator
      interval: 5m
  releaseName: prometheus-operator
  values:
    replicas: 1
    service:
      type: LoadBalancer
      port: 80