apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus
spec:
  interval: 1m
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus
      interval: 5m
  releaseName: prometheus
  values:
    replicas: 1
    service:
      type: LoadBalancer
      port: 80
    server:
      persistence:
        enabled: true
        size: 8Gi
        storageClassName: persistentvolume-controller
    persistentVolume:
      enabled: true
      name: persistentvolume-controller
      capacity: 15Gi
      accessModes:
        - ReadWriteOnce
      hostPath:
        path: /prometheus/data
    storageClass:
      name: persistentvolume-controller
      provisioner: kubernetes.io/no-provisioner
      volumeBindingMode: WaitForFirstConsumer