apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: product-service
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./manifest/k8s-development
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system