apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: development
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./manifest/k8s-development/namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age