apiVersion: apps/v1
kind: Deployment
metadata:
  name:  product
  namespace: default
  labels:
    app:  product
spec:
  selector:
    matchLabels:
      app: product
  replicas: 1
  template:
    metadata:
      labels:
        app:  product
    spec:
      containers:
      - name:  product
        image:  nginx:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
    
        ports:
        - containerPort:  80