apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: legacy-pod
spec:
  selector:
    matchLabels:
      app: legacy-pod
  serviceName: legacy-pod
  template:
    metadata:
      labels:
        app: legacy-pod
    spec:
      containers:
      - name: legacy-pod
        image: nicolaka/netshoot
        command: ["tail",  "-f", "/dev/null"]