apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kiali
spec:
  interval: 1m
  chart:
    spec:
      chart: kiali-server
      sourceRef:
        kind: HelmRepository
        name: kiali
      interval: 5m
  releaseName: kiali
  values:
    replicas: 1
    service:
      type: NodePort
      port: 80