apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kiali-monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: kiali
      sourceRef:
        kind: HelmRepository
        name: kiali
      interval: 5m
  releaseName: kiali-monitoring
  values:
    replicas: 1
    service:
      type: LoadBalancer
      port: 80