apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 5m
  releaseName: grafana
  values:
    replicas: 1
    service:
      type: LoadBalancer
      port: 80
    server:
  persistence:
    enabled: true
    size: 8Gi
    storageClassName: persistentvolume-controller
