apiVersion: v1
kind: Service
metadata:
  name: product-baru-svc
spec:
  type: LoadBalancer
  selector:
    app: product-baru-svc
  ports:
  - name: product-baru-svc
    protocol: TCP
    port: 80
    targetPort: 3000
    